// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  product_feature: dynamic(() => import("./ProductFeature")),
  scroll_text: dynamic(() => import("./ScrollText")),
};
